<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5243d613-4ebc-4f6d-a5ab-6fb17a4ff035</elementGuidId>
    <imagePath></imagePath>
    <name>link_wirelessChargingStand</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[6]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="products__item\ in-stock\ products__item_3-in-row"]:nth-child(6) [class="products__title"] &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/3-in-1-wireless-charging-stand-with-magsafe?sort=price') and equals(@text,'3-in-1 Wireless Charging Stand with MagSafe')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name="3-in-1 Wireless Charging"i] &gt;&gt; internal:role=link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/3-in-1-wireless-charging-stand-with-magsafe?sort=price</value>
        <webElementGuid>98d84f0f-d09a-44b4-9e55-fcea3a119a64</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>3-in-1 Wireless Charging Stand with MagSafe</value>
        <webElementGuid>98d84f0f-d09a-44b4-9e55-fcea3a119a64</webElementGuid>
    </webElementProperties>
</WebElementEntity>