<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>faada3cf-7d82-4705-bc0f-b43f943bf468</elementGuidId>
    <imagePath></imagePath>
    <name>link_productSamsungGalaxyS23UltraSmartviewCases</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/h4[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/samsung-galaxy-s23-ultra-smartview-cases') and equals(@text,'Samsung Galaxy S23 Ultra Smartview Cases')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=heading[name="Samsung Galaxy S23 Ultra"i] &gt;&gt; internal:role=link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/samsung-galaxy-s23-ultra-smartview-cases</value>
        <webElementGuid>9d446125-ef44-4801-9fe2-e8d15cf05e40</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Samsung Galaxy S23 Ultra Smartview Cases</value>
        <webElementGuid>9d446125-ef44-4801-9fe2-e8d15cf05e40</webElementGuid>
    </webElementProperties>
</WebElementEntity>