<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b0058e96-3676-4d36-9e52-b899c82730af</elementGuidId>
    <imagePath></imagePath>
    <name>link_byPrice</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/div[1]/div[2]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="sort-buttons__element"]:nth-child(3) &gt; [class="sort-buttons__link"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#') and equals(@text,'By price')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="By price"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>98d84f0f-d09a-44b4-9e55-fcea3a119a64</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>By price</value>
        <webElementGuid>98d84f0f-d09a-44b4-9e55-fcea3a119a64</webElementGuid>
    </webElementProperties>
</WebElementEntity>